__title__ = 'Shockfish'
__version__ = '0.0.1'
__author__ = 'Denis Kolegov, Positive Technologies Application Firewall Research Team'
__author_email__ = 'dkolegov@ptsecurity.com'
__description__ = 'A training experimental vulnerable web application firewall.'